// This file defines Macros and Attributes defined in CLI header files
// It is exported by odbc.js so that all get available for application
// Application can use it as ibmdb.SQL_ATTR_PARAMSET_SIZE instead of 22

module.exports = {
    // Statement Attributes
    SQL_ATTR_QUERY_TIMEOUT : 0,
    SQL_ATTR_PARAM_BIND_TYPE : 18,
    SQL_ATTR_PARAMSET_SIZE : 22,
    SQL_ATTR_ROW_ARRAY_SIZE : 27,

    // InfoType for SQLGetInfo i.e. ibmdb.getInfo()
    // Defined in sqlcli1.h
    SQL_DATA_SOURCE_NAME : 2,
    SQL_FETCH_DIRECTION : 8,
    SQL_SERVER_NAME : 13,
    SQL_SEARCH_PATTERN_ESCAPE : 14,
    SQL_ODBC_SQL_CONFORMANCE : 15,
    SQL_DATABASE_NAME : 16,
    SQL_DBMS_NAME : 17,
    SQL_DBMS_VER : 18,
    SQL_ACCESSIBLE_TABLES : 19,
    SQL_ACCESSIBLE_PROCEDURES : 20,
    SQL_PROCEDURES : 21,
    SQL_CONCAT_NULL_BEHAVIOR : 22,
    SQL_CURSOR_COMMIT_BEHAVIOR : 23,
    SQL_CURSOR_ROLLBACK_BEHAVIOR : 24,
    SQL_DATA_SOURCE_READ_ONLY : 25,
    SQL_DEFAULT_TXN_ISOLATION : 26,
    SQL_EXPRESSIONS_IN_ORDERBY : 27,
    SQL_IDENTIFIER_CASE : 28,
    SQL_IDENTIFIER_QUOTE_CHAR : 29,
    SQL_MAX_COLUMN_NAME_LEN : 30,
    SQL_MAX_CURSOR_NAME_LEN : 31,
    SQL_MAX_SCHEMA_NAME_LEN : 32,
    SQL_MAX_PROCEDURE_NAME_LEN : 33,
    SQL_MAX_TABLE_NAME_LEN : 35,
    SQL_MULT_RESULT_SETS : 36,
    SQL_MULTIPLE_ACTIVE_TXN : 37,
    SQL_OUTER_JOINS : 38,
    SQL_PROCEDURE_TERM : 40,
    SQL_TXN_CAPABLE : 46,
    SQL_USER_NAME : 47,
    SQL_MAX_COLUMNS_IN_SELECT : 100,
    SQL_MAX_COLUMNS_IN_TABLE : 101,
    SQL_MAX_INDEX_SIZE : 102,
    SQL_MAX_ROW_SIZE : 104,
    SQL_MAX_STATEMENT_LEN : 105,
    SQL_DBMS_FUNCTIONLVL : 203,
    SQL_DATABASE_CODEPAGE : 2519,
    SQL_APPLICATION_CODEPAGE : 2520,
    SQL_CONNECT_CODEPAGE : 2521,
    SQL_DB2_DRIVER_VER : 2550,
    SQL_DRIVER_BLDLEVEL : 2604,
    SQL_XOPEN_CLI_YEAR : 10000,
    // sqlext.h
    SQL_DRIVER_NAME : 6,
    SQL_DRIVER_VER :7,
    SQL_ODBC_API_CONFORMANCE : 9,
    SQL_ODBC_VER : 10,
    SQL_ROW_UPDATES : 11,
    SQL_ODBC_SAG_CLI_CONFORMANCE : 12,
    SQL_DATABASE_NAME : 16,
    // fetchMode
    FETCH_ARRAY : 3,
    FETCH_OBJECT : 4,
    FETCH_NODATA : 0,

    // InfoType for SQLGetTypeInfo i.e. ibmdb.getTypeInfo()
    // Defined in sqlcli1.h and sqlext.h
    ALLTYPES : 0, //SQL_ALL_TYPES
    BIGINT : -5, //SQL_BIGINT
    BINARY : -2,
    BIT : -7,
    BLOB : -98,
    BOOLEAN : 16,
    CHAR : 1,
    CLOB : -99,
    DATE : 91, //SQL_TYPE_DATE
    DBCLOB : -350,
    DECIMAL : 3,
    DOUBLE : 8,
    FLOAT : 6,
    GRAPHIC : -95,
    INTEGER : 4,
    LONGVARBINARY : -4,
    LONGVARCHAR : -1,
    LONGVARGRAPHIC : -97,
    NUMERIC : 2,
    REAL : 7,
    SMALLINT : 5,
    TIME : 92, //SQL_TYPE_TIME
    TIMESTAMP : 93, //SQL_TYPE_TIMESTAMP
    TINYINT : -6,
    VARBINARY : -3,
    VARCHAR : 12,
    VARGRAPHIC : -96,
    XML : -370,

}

